### ISSUE TITLE
Allow a build to restart in the middle

### ISSUE THREAD

**Issue by citibob** [hpcugent/easybuild-framework#1531]
Just like there's an option to run a build only through a certain step... there should also be one to START the build at a certain step (assuming the last time the build was run, it got at least that far).  This would be VERY useful for the following situation I'm commonly encountering:

1. Try a new .eb.  Wait 5 minutes for it to download and compile.
2. Discover a problem with the sanity check in the easyblock or easyconfig.
3. Re-run the build.  Wait another 5 minutes, cross my fingers I didn't make a typo trying to fix the sanity check.
4. If there's a problem, goto step 2, it's gonna be a long night...

**Comment by boegel** [comment]
This is a reasonable request, but hard to implement in practice...

Previous steps may have made changes in the environment for example, and not having these around anymore may result in a slightly different build procedure being executed. There are other things to keep in mind as well, which make this difficult to implement. See also issue #203.

It may not be impossible though, especially now that we have `--extended-dry-run` available... 
We could rerun previous steps in dry run mode, where changes to the environment are still made (since they're cheap), but executing commands is skipped.

For your particular problem however, i.e. only rerunning the sanity check step and then generating the module, we do have a solution: `--module-only`, cfr. http://easybuild.readthedocs.org/en/latest/Partial_installations.html#module-only .

If you use `--module-only` *without* `--force`, EasyBuild will (re)run the sanity check to make sure the installation is already in place as it should be, and generate the module file in case the sanity check passes.

Please check issue #203. If you feel that issue covers your request well, please close this issue as a duplicate, and drop a comment in #203.

**Comment by citibob** [comment]
Thank you for the update.  A few thoughts:

1. This is for developing/testing, the feature does not have to be bullet-proof.  Especially if there's a way to tell it to just start over from the beginning (it looks like --force is useful here).

2. I reported recently that GCC didn't build.  Consider how one might debug this problem (the build stopped somewhere during stage1).  The following would be a plausible way to debug:

  a) Have a mode where EasyBuild downloads source from a repo rather than tarball; or do this by default ("git clone --depth 1 --branch 17.34" now works well)

 b) Run EasyBuild, wait until it crashes

 c) "Manually" go in and edit files.  Either the source code is bad (in which case you only have to say "make"), or the configure scripts are bad (in which case you will have to ask EasyBuild to re-run the configure procedure).

 d) Once you get it working, commit the changes to some repository, which returns a hash.  Change the "git clone" command in the .eb file to check out this version.

e) Clean out the module file, then re-run the build process from scratch to see that it works.

**Comment by boegel** [comment]
I agree with you that it doesn't need to be bullet proof, but that doesn't necessarily imply less effort to make it useful enough in practice.
The issue with GCC is even more complex, since there the procedure is failing somewhere in the middle of the '`build`' step. If we ever add support for `--continue`, it will most likely be to restart the last step that failed, so in the GCC case we would *redo* the stage 1 build.
