### ISSUE TITLE
Switching between naming schemes

### ISSUE THREAD

**Issue by ocaisa** [hpcugent/easybuild-framework#1535]
One major hurdle when switching between naming schemes is that the default installation directory is [dependent on the naming scheme](https://github.com/hpcugent/easybuild-framework/blob/bbd3b0ce82b4d67319d7cd934ead9c45e1cc5ff7/easybuild/tools/module_naming_scheme/mns.py#L97). This is unnecessary since the module files themselves don't care where the installation is. Changing the default to a unique value, for example that used by [easybuild_mns.py](https://github.com/hpcugent/easybuild-framework/blob/541556488193cc917c2478f2134ae1e51bbde7d4/easybuild/tools/module_naming_scheme/easybuild_mns.py), would make switching naming schemes relatively trivial via a simple script:
* Search for all installed easyconfigs in the installation space (no need to know what MNS was used to install them)
* Parse them
* Check existing module from old naming scheme to see if it is hidden, set flag if it is
* Rebuild all easyconfigs using `--module-only` with new MNS

I even think the default naming scheme tree should be created regardless of the naming scheme actually used just so you only need to indicate the new MNS when creating a new module tree.

**Comment by ocaisa** [comment]
Changing this would be backwards compatible for everyone already using the new default and would work also work seamlessly for other supported naming schemes (but they would not be able to change naming scheme via the new script since only the new software would be in the *correct* installation path)

**Comment by boegel** [comment]
@ocaisa: supporting using a fixed naming scheme for the installation directories makes a lot of sense indeed, I'm just not sure it's a good idea to make this the *default*

Although EasyBuild itself or existing modules/installations won't mind, people may have made assumptions on the naming scheme used for the installation in other places, e.g. a script that crawls the installation directories (for whatever reason).

So, your backward compatibility argument is not 100% correct.

That said, we do have some other options if we do want to change the default to using a fixed naming scheme:

* make sure people can opt-out easily, e.g. with `--disable-fixed-install-dir-naming-scheme` or whatever
* be very verbal about changing the default (mentioning it on the ML in a separate post, in the release notes, and in the release announcement, comments in the code where the name of the install directory is decided on, etc.)
* indicate that the naming scheme of the modules and the install directories doesn't match every time `eb` is run, with an option to silence that warning (maybe even with a generic `--slience-warnings=module-vs-install-dir-naming-scheme-mismatch`); maybe that's a bit over the top though, I'm not sure

You mentioned you were going to look into implementing this yourself, thanks for that. Let's do that first, and then consider switching the default behaviour. I'm willing to consider it since i) it makes a lot of sense, ii) the impact is low, iii) we can poll up front via the ML whether this may impact people in one way or another.

**Comment by boegel** [comment]
support for `--fixed-installdir-naming-scheme` configuration option added in #1546 

@ocaisa: ok to close this?

**Comment by ocaisa** [comment]
Thanks!
