### ISSUE TITLE
unittest failure: 'module' object has no attribute 'file'

### ISSUE THREAD

**Issue by andreas-h** [hpcugent/easybuild-framework#1672]
I'm on Debian Stretch, with Python 2.7.  I followed the documented bootstrapping procedure and run into trouble with the unit testing:

    $ module use .local/easybuild/modules/all/
    $ module load EasyBuild
    $ module list
    
    Currently Loaded Modules:
      1) EasyBuild/2.6.0
    
    $ eb --version
    This is EasyBuild 2.6.0 (framework: 2.6.0, easyblocks: 2.6.0) on host shaula.
    
    $ export TEST_EASYBUILD_MODULES_TOOL=Lmod
    
    $ python -m test.framework.suite
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home2/hilboll/.local/easybuild/software/EasyBuild/2.6.0/lib/python2.7/site-packages/easybuild_framework-2.6.0-py2.7.egg/test/framework/suite.py", line 47, in <module>
        keyring.set_keyring(keyring.backends.file.PlaintextKeyring())
    AttributeError: 'module' object has no attribute 'file'

So here I'm reporting, as asked for in the bootstrap documentation.

Thanks for your great work!

**Comment by boegel** [comment]
This is a known issue, which has been fixed already, see https://github.com/hpcugent/easybuild-framework/pull/1650 .

The fix will be part of EasyBuild v2.7.0, which will be released in the next couple of days.

Fixing this issue is fairly easy, see https://github.com/hpcugent/easybuild-framework/pull/1650/files, maybe you can apply that patch manually to your installation?

**Comment by andreas-h** [comment]
thanks, that worked like a charm :-)
