### ISSUE TITLE
--show-config not working with --include-easyblocks

### ISSUE THREAD

**Issue by gppezzi** [hpcugent/easybuild-framework#1696]
While --include-easyblocks seems to work correctly, if I try to use --show-config easybuild crashes (very early, before creating the log file).

Here's the log (with export DEBUG_EASYBUILD_OPTIONS=1):
https://gist.github.com/gppezzi/6989e51272fc3bad20b8

If I remove --include-easyblocks, then show-config works.

**Comment by boegel** [comment]
#1705 fixes this problem, and adds a test for it

Basically the problem was that `--show-config` redoes the configuration a couple of times, to figure out at what level each configuration option is defined. It was setting up the included easyblocks & co every time too though, which doesn't work.

#1705 works around that by not setting up the included Python modules over and over again, basically.

Let's follow up there, thanks for reporting this @gppezzi!
