### ISSUE TITLE
--module-only overwrites buildstats in archived easyconfig

### ISSUE THREAD

**Issue by geimer** [hpcugent/easybuild-framework#1947]
As the title already says, regenerating a module file using `--module-only` overwrites the `buildstats` list written to the archived easyconfig.  Usually, this shouldn't be big deal, however, http://easybuild.readthedocs.io/en/latest/Submitting_jobs.html suggests that at least the `build_time` parameter is taken to calculate the maximum walltime when using `--job`.

Now, consider a package such as `GCCcore` - which takes quite some time to build - and regenerate the module file.  The build time stored in the archived easyconfig will now be in the order of a second... and a rebuild of the package is guaranteed to hit the wall-clock limit...

**Comment by boegel** [comment]
@geimer hmm, that's indeed annoying...

So, what *should* it do?

I think we want it to update the archived easyconfig file (since the whole reason of using `--module-only` may be that it got tweaked), but we would also like to have build stats in it... Should those be inherited from an easyconfig that is already in the archive? Or maybe just partially?

**Comment by geimer** [comment]
@boegel I think everything except for the `build_time` (and maybe the `timestamp`?) could be overwritten.  Maybe we could add a comment that a value was inherited from a previous install?

**Comment by geimer** [comment]
@boegel Thinking about it again, maybe the *build*_stats shouldn't change at all, as the build itself didn't change?

**Comment by boegel** [comment]
fixed in #1956, I suggest we follow up there @geimer?
