### ISSUE TITLE
make EasyBuild add patches to easyconfig repository

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-framework#198]
(old internal ticket 267)

Patch files should also be added in the easyconfig repository after building, next to the easyconfig file with added build statistics.

**Comment by geimer** [comment]
Note from a discussion with @boegel at the 8th EasyBuild hackathon: Since patches modify the source code of a package, it may make sense to archive them next to the sources instead of the easyconfig repository. However, in the end the location doesn't matter that much as long as the patch file is archived at all.

**Comment by ocaisa** [comment]
With the new features of easybuild it may be the case that the user can use a custom easyblock for the installation via the command line, for true reproducability we should probably include the easyblock in the easybuild subdir of the installation

**Comment by boegel** [comment]
@ocaisa: that sounds like a versioning nightmare... I understand why you're concerned about that though.
Do you feel copying the easyblock should always be done (even if `--include-easyblocks` was not used)?
Should this be configurable behaviour?

**Comment by ocaisa** [comment]
What do you think? It's not a lot of overhead to include the block in all cases (in the install space only). If it were to be configurable I'd be for a default of true since this is fundamental to reproducability.
How deep does `include-easyblocks` go? For example, if I had
```
--include-easyblocks=block1.py,block2.py
```
is it possible for `block2` to inherit from `block1`? That would complicate this further.

**Comment by boegel** [comment]
Of course, `--include-easyblocks` simply adds additional easyblocks that EB can use.

It's even possible to use `--include-easyblocks=generic/configuremake.py`, and then to use an (existing) easyblock that derives from the customised `ConfigureMake`...

So, not trivial indeed.

**Comment by boegel** [comment]
fixed in #2202
