### ISSUE TITLE
Allow root to execute eb

### ISSUE THREAD

**Issue by dominikborkowski** [hpcugent/easybuild-framework#420]
Currently easybuild refuses to run when executed under root account. While it's often prudent to have separate accounts for compile processes, it seems that this should be an option, rather than a forced requirement. 

What would be nice is to have `--allow-root`/`--allow-superuser`/`--allow-admin` or similar option, that would allow an override of this behavior. 

Cheers!

**Comment by fedepad** [comment]
What's the status? Because I don't see this thing in the repo: downloaded the (latest?) bootstrap_eb.py as described in the website but fails as root. .
In my case I have a system that I use always as root (no multi-user....); I think "not being root" as a requirement it's not the best idea: probably make it as a default option that is configurable though in case someone who knows what is doing wants to just run and try.

**Comment by boegel** [comment]
@fedepad Support for allowing to run as `root` is implemented in a straightforward way in https://github.com/hpcugent/easybuild-framework/pull/2123 .

That means that `--allow-use-as-root` will be supported in a future EasyBuild release (under the condition that the PR gets reviewed/approved/merged), so you should be able to bootstrap as `root` after running `export EASYBUILD_ALLOW_USE_AS_ROOT=1` soonish.

**Comment by fedepad** [comment]
@boegel Thank you very much for the explanation! Appreciated!

**Comment by fedepad** [comment]
I was able after a while (a lot...) to build, install Easybuild with your patch and load the "main" module. Now I execute:  

`eb mpiBLAST-1.6.0-goolf-1.4.10.eb --robot`
and I get:
> == temporary log file in case of crash /tmp/eb-2Trx7U/easybuild-he0M0p.log
> ERROR: You seem to be running EasyBuild with root privileges which is not wise, so let's end this here.

How can this be solved **QUICKLY**?

**Comment by ocaisa** [comment]
The quickest thing to do would be to not use `root` and take the more standard approach that is well documented. 

Installing EB with `root` is one thing since @boegel know what the source does, installing all software through EB with `root` is another, how can you know that what you are doing is in any way secure? The EasyBuild recipes are community developed and not checked for security (they don't need to  be if they are installed in user space).

**Comment by boegel** [comment]
The security concern is broader than just EasyBuild: you're running scripts, Makefiles, etc. from a random source on the worldwide web, and there have been (unintended) problems with stuff like that before (google "bumblebee github fail" to see a 'nice' example).

**Comment by boegel** [comment]
@fedepad w.r.t. support for running `eb` with `root` privileges, this will only be supported in EasyBuild v3.2.0 at the earliest, *if* pull request https://github.com/hpcugent/easybuild-framework/issues/2123 gets merged (there's some disagreement on how the command line option should be named)

**Comment by boegel** [comment]
Support for configuring EasyBuild with `--allow-use-as-root-and-accept-consequences` will be included in the upcoming EasyBuild v3.2.0 via #2123, so closing this.
